# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginWithNoSubscriptions

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r flask flask-sqlalchemy

    - name: test with PyTest
      run: pytest --cov=app --cov-report=xml
      
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !venv/
          
    - uses: actions/download-artifact@v2
      with:
        name: python-app
        path: .

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

    - name: Configure deployment and runtime settings on the webapp
      run: |
        az configure --defaults ${{ env.RESOURCE_GROUP }}
        az webapp config appsettings --name ${{ env.WEBAPP_NAME }} --settings \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            FLASK_ENV=production

        az webapp config set --name ${{ env.WEBAPP_NAME }} \
            --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app:app"
            
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME}}
    
    
